### ISSUE TITLE
Ethereum에서 EOS로 가는 것에 대한 보상 정책 변경

### ISSUE THREAD

**Issue by ghost** [kookmin-sw/2018-cap1-29#10]
정책 변경 요청합니다.

**Comment by toms0124** [comment]
이오스 토큰 소유자로부터 투표를 받으면 투표 받은 비율에 따라 신규발행 이오스 토큰을 분배받습니다. 그리고 이 때 분배받은 토큰은 밴드위스 확보를 위해 매물화 가능성이 줄어들게 됩니다. 댑 사업자가 댑 사용자로부터 돈을 벌기 위한 수익모델을 고민하지 않아도 됩니다. 이오스 토큰 소유자로부터 투표를 받을 수 있다면 댑 자체도 무료 서비스가 가능해 지는 것입니다.
댑 사업자는 이오스 토큰 보유자에게 투표를 받아야 함으로 사업자는 최고 수준의 댑 서비스를 제공하기 위해 노력하게 되며 이오스 토큰 보유자를 위한 다양한 투표 유인 정책을 시행하게 될 것으로 예상 됩니다.
사업자는 댑이 활성화 될수록 자신이 가진 이오스 토큰의 가치가 오르게 됨으로 추가 수익을 기대할 수 있게 됩니다.
댑 사용자는 무료수수료로 댑을 사용할 수 있으므로 사업자는 더 많은 사용자 유치에 유리합니다.
사업자가 이오스 토큰이 필요하지만 토큰을 구입할수 없다면 이오스 토큰 소유자로부터 토큰을 임대할수 있으므로 실질적 사업 비용을 큰 폭으로 줄일 수 있습니다.
